# Generated by Django 5.2.8 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('audience', models.CharField(choices=[('general', 'Для всех'), ('adults', 'Взрослая аудитория'), ('kids', 'Детская аудитория')], default='general', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
    ]
